import { pdfjs } from 'react-pdf';

let configured = false;

export function configurePdfWorker() {
  if (configured) return;

  // Prefer local worker URL generated by Vite; avoid remote CDN worker issues on mobile browsers.
  const localWorkerUrl = new URL('pdfjs-dist/build/pdf.worker.min.mjs', import.meta.url).toString();
  pdfjs.GlobalWorkerOptions.workerSrc = localWorkerUrl;
  configured = true;
}

